### PR TITLE
Added close function

### PR DESCRIPTION
**Pull request by fjafferi**
Close function to close current window

### CODE REVIEW

**Comment by highfestiva** [comment]
Mm. That does not work. Variable `win` is not declared for one. Next time, test your code to see that it at least does what it's supposed to in a happy flow.

**Review by fjafferi — COMMENTED** [review]
let's try this again. Got trigger happy and accidently pasted the wrong piece of code.

**Comment by highfestiva** [comment]
I would very much prefer if you'd put the try-except inside the loop instead. That way some may fail, but others could still work. Perhaps also print something if it fails? See the other except statements in the file.

**Comment by fjafferi** [comment]
done.

**Comment by highfestiva** [comment]
Added the function, but had to scrap your pull request unfortunately. I can recommend [How To Write a Git Commit Message](https://chris.beams.io/posts/git-commit/) and also pre-[squashing](https://www.git-tower.com/learn/git/faq/git-squash/) your commits for ease of use.

**Pull request closed without merging**
