### PR TITLE
Hide crosshair when mouse pointer is not over the plot otherwise show it

### PR DESCRIPTION
**Pull request by shujaatak**
This commit lets finplot to show crosshair(if enabled) when the mouse pointer is over the plot else hide the crosshair to reduce the clutter produced by it.

### CODE REVIEW

**Comment by highfestiva** [comment]
Looks good, did you test the examples with this change?

**Comment by shujaatak** [comment]
> Looks good, did you test the examples with this change?

I have tested some examples(as other examples not even work with old commits) with this change. I have noticed that crosshair code works perfectly. For example you can check this pull request with [complicated.py](https://github.com/highfestiva/finplot/blob/master/finplot/examples/complicated.py) example.

NOTE some examples do not even work with old [commit](https://github.com/highfestiva/finplot/commit/1190e8af6e181c4faf0d4be012eca9102ed7fd71) which reads "Make sure we're rounding .5 up" so I couldn't test them. Few examples which doesn't even work with old commits: [animate.py](https://github.com/highfestiva/finplot/blob/master/finplot/examples/animate.py), [pandas-df-plot.py](https://github.com/highfestiva/finplot/blob/master/finplot/examples/pandas-df-plot.py)

**Comment by highfestiva** [comment]
pyqtgraph complains that finplot is adding the crosshair twice:
```
Python39\lib\site-packages\pyqtgraph\graphicsItems\PlotItem\PlotItem.py:522: UserWarning: Item already added to PlotItem, ignoring.
  warnings.warn('Item already added to PlotItem, ignoring.')
```

There needs to be some check in inside or outside crosshair's `show()` so it doesn't call `addItem()` twice.

**Comment by shujaatak** [comment]
As I moved the call to addItem() to constructor so now it will only be called once, hence, pyqtgraph will never show the following warning again:

> Python39\lib\site-packages\pyqtgraph\graphicsItems\PlotItem\PlotItem.py:522: UserWarning: Item already added to PlotItem, ignoring.
  warnings.warn('Item already added to PlotItem, ignoring.')

**Comment by highfestiva** [comment]
Unfortunately this broke the crosshair in four examples, for instance `complicated.py` and `dockable.py`. Please fix that before I'll merge.

**Comment by shujaatak** [comment]
I was amazed when I found that `compicated.py` did not show crosshair  although I add `vline, hline, xtext and ytext` items to `ax` in `FinCrossHair` constructor!

I checked whether the crosshair's items somehow get removed due to which they do not show up by using the following code in the `FinCrossHair's show() `function:
```
        if self.vline in self.ax.items:
            print('Crosshair present.')
        else:
            print("Crosshair not present.") 
```
Surprisingly the crosshair's `vline` and similarly it's other items were not present in `self.ax.items`!

So I started finding out where these crosshair's items get removed. As only a few examples had this issue so I was sure the problem originates from the examples. I looked in the code of `complicated.py` example and found that if I comment out [ax.reset()](https://github.com/highfestiva/finplot/blob/d7212945e70efd2f7d7594ee1cc61b259da5726c/finplot/examples/complicated.py#L267) and  [ax_rsi.reset()](https://github.com/highfestiva/finplot/blob/d7212945e70efd2f7d7594ee1cc61b259da5726c/finplot/examples/complicated.py#L269) then the issue gets resolved and the crosshair show up as it should be and hides when the mouse leaves the plot.

**Now I have got a question which is** why ax.reset() removes the crosshair? Is it possible to make `ax.reset() `to not remove crosshair as I have noticed that ax still use the same `FinCrossHair` object but removes the crosshair items?

By the way, I really like showing and hiding items rather than adding and removing although I don't know which one is most efficient method.

**Comment by shujaatak** [comment]
I have a very simple workaround solution which would also work even if `ax.reset() `and `ax_rsi.reset() etc.` are present. and that is to show crosshair items if they are present in `ax` else add them to `ax` in the `FinCrossHair's show() `function:
```
        if self.vline in self.ax.items:
            self.vline.show()
            self.hline.show()
            self.xtext.show()
            self.ytext.show()
        else:
            self.ax.addItem(self.vline, ignoreBounds=True)
            self.ax.addItem(self.hline, ignoreBounds=True)
            self.ax.addItem(self.xtext, ignoreBounds=True)
            self.ax.addItem(self.ytext, ignoreBounds=True)
```

**Comment by shujaatak** [comment]
As you might have noticed that the neatest solution is to make ax.reset() to not remove crosshair by default.

**Comment by shujaatak** [comment]
dockable.py also call the same `reset() `function which is why the crosshair doesn't appear. 

I wonder why we need this `ax0.reset() # remove previous plots` explicitly in our examples? what previous plots they remove?

**Comment by shujaatak** [comment]
The latest commit solves the issue with the rest of the examples now.

**Comment by highfestiva** [comment]
Hiding of the crosshair in `examples/analyze-2.py` no longer works:
```python
ax5.set_visible(crosshair=False, xaxis=False, yaxis=False) # hide junk for a more pleasing look
```
Since there's been so many hickups, may I ask what the value of this fix is? In what way does it simplify for our users. It's a functionality that must be maintained indefinitely if added. I'm getting concerned as I myself don't see any value in it, but the edge cases keeps tripping it up.

**Comment by shujaatak** [comment]
The following code should **disable** crosshair:
```
ax5.set_visible(crosshair=False, xaxis=False, yaxis=False) # hide junk for a more pleasing look
```
But as you can see in the following code the crosshair is set to only `hide` so it definitely would be shown again by the `FinCrossHair.show `function when the mouse is brought over the plot:
```
def _ax_set_visible(ax, crosshair=None, xaxis=None, yaxis=None, xgrid=None, ygrid=None):
    if crosshair == False:
        ax.crosshair.hide()
```
We need an api to disable crosshair so that even if `ax.crosshair.show() `is called the crosshair should not show up until it is enabled again. I would create a new commit soon so that crosshair can be enabled and disabled by `ax.crosshair.enable()` and `ax.crosshair.disable()` respectively.

**Value:**
The crosshair which stays there in the plot even when user doesn't intend to read crosshair location's values but he/she see the crosshair even when the mouse is somewhere else then the crosshair value is nothing but clutter.
In my opinion, the plot should look neat and clean without crosshair when the user doesn't have mouse pointer over the plot. In the current state, when a user move mouse pointer out of the plot, the crosshair is displayed at the edge where the mouse pointer leaves the plot.

**Comment by shujaatak** [comment]
With the latest commit, now hiding of the crosshair in `examples/analyze-2.py` will work as expected.

**Comment by highfestiva** [comment]
Wouldn't a hot-key for toggle hiding/showing of the crosshair be better? Then you could hide it for screenshots while in the foreground (or whatever other purpose).

**Comment by shujaatak** [comment]
Personally I don't like to remember hot-keys for functionality that I think should be there by default.

**Comment by highfestiva** [comment]
Sorry, but this is too much code and too many edge cases for too little value. I cannot keep it, as a service to me and the users of this lib. You could create an "add-on" which you import, which modify the finplot api with the stuff you want. GL!

**Pull request closed without merging**
