### PR TITLE
new example

### PR DESCRIPTION
**Pull request by degloff**
New example using cryptofeed, plotting realtime candles, including volume and orderbook profile

### CODE REVIEW

**Comment by highfestiva** [comment]
Thanks for the well-written example! Bad news first: I'm not going to incorporate this as an example straight out of the box. The good news is that it's well-written and valuable. Here's what I'm thinking: it's too big to be an example. Bytes on disk:

image

But it doesn't show any aspects of finplot that isn't shown elsewhere? It's more like an application. Something that *would* be valuable to many users is a large-scale application containing *all* of the major features, where they're able to switch between crypto and stock. So we could have a single go-to application, in which we add every single feature that exists now and in the future. It could also contain some additional features, such as comparing currencies, etc. People could use it as an alternative to tradingview, with endless possibilities.

What do you think? Would you consider extending your code to accommodate this? Could you also consider mainting that code? That would be awesome for me, as I could focus on the core, and you on how to utilize it best and create the most value for the users.

I also have two more features that I'm considering, but that's a different topic for later.

**Comment by degloff** [comment]
Hi Jonas

Thanks for the reply.

Oh you have a good point. Did not look into the size. Fully agree. It is more like an app.

I can try to add some more features to the app over time and feed it back. A full blown alternative to TradingView is quite ambitious, but with QT and your start may be doable.

I am happy to feed back my work gradually. May just need a bit of time.

**Comment by highfestiva** [comment]
Closing this for now, make a new pull request if you ever take on the challenge of a full-blown app. Here's one feature request for that, if you need some extra work: https://github.com/highfestiva/finplot/issues/82 :)

**Comment by gryabov** [comment]
It would be great to create a separate repo for (heavy) examples.

**Comment by highfestiva** [comment]
@gryabov I'm all for it, please commence and I'll incorporate it. Even "heavy" examples take very little space, so perhaps not necessary with a separate repository.

**Pull request closed without merging**
